name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Show softuni name
      run: echo 'viktorshterev'

  execute_ui_tests:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start app
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui

  deploy:
    needs: execute_ui_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          
